[tool.briefcase]
project_name = "TFT Interpreter"
bundle = "com.example"
version = "0.0.1"
url = "https://github.com/BrianHotopp/beeware-interpreter"
license = "Other"
author = 'Brian Hotopp'
author_email = "brihoto@gmail.com"

[tool.briefcase.app.tftinterpreter]
formal_name = "TFT Interpreter"
description = "TFT Assistant"
icon = "src/tftinterpreter/resources/tftinterpreter"
sources = ['src/tftinterpreter']
requires = [
"arrow==1.2.2",
"binaryornot==0.4.4",
"briefcase==0.3.6",
"certifi==2021.10.8",
"cffi==1.15.0",
"chardet==4.0.0",
"charset-normalizer==2.0.12",
"click==8.1.2",
"clr-loader==0.1.7",
"colorama==0.4.4",
"colosseum==0.2.0",
"cookiecutter==1.7.3",
"cycler==0.11.0",
"detecto==1.2.2",
"fonttools==4.33.2",
"gitdb==4.0.9",
"GitPython==3.1.27",
"idna==3.3",
"Jinja2==3.1.1",
"jinja2-time==0.2.0",
"kiwisolver==1.4.2",
"MarkupSafe==2.1.1",
"matplotlib==3.5.1",
"numpy==1.22.3",
"opencv-python==4.5.5.64",
"packaging==21.3",
"pandas==1.4.2",
"Pillow==9.1.0",
"poyo==0.5.0",
"pycparser==2.21",
"PyGetWindow==0.0.9",
"pyparsing==3.0.8",
"PyRect==0.2.0",
"python-dateutil==2.8.2",
"python-slugify==6.1.1",
"pythonnet==3.0.0a2",
"pytz==2022.1",
"pywin32==303",
"requests==2.27.1",
"six==1.16.0",
"smmap==5.0.0",
"text-unidecode==1.3",
"toga==0.3.0.dev32",
"toga-core==0.3.0.dev32",
"toga-winforms==0.3.0.dev32",
"toml==0.10.2",
"torch==1.11.0",
"torchvision==0.12.0",
"tqdm==4.64.0",
"travertino==0.1.3",
"typing_extensions==4.2.0",
"urllib3==1.26.9"
]


[tool.briefcase.app.tftinterpreter.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev32',
    'std-nslog==1.0.0'
]

[tool.briefcase.app.tftinterpreter.linux]
requires = [
    'toga-gtk>=0.3.0.dev32',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.tftinterpreter.windows]
requires = [
    'toga-winforms>=0.3.0.dev32',
]

# Mobile deployments
[tool.briefcase.app.tftinterpreter.iOS]
requires = [
    'toga-iOS>=0.3.0.dev32',
    'std-nslog==1.0.0'
]

[tool.briefcase.app.tftinterpreter.android]
requires = [
    'toga-android>=0.3.0.dev32'
]
